server {
  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    # Essencial para que o roteamento do React funcione
    try_files $uri $uri/ /index.html;
  }
}